name: Cake

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - uses: azure/docker-login@v1
      with:
        login-server: 'prxmdocker.azurecr.io' 
        username: '${{ secrets.azure_docker_user }}'
        password: '${{ secrets.azure_docker_token }}'

    - name: Start Docker for MSSSql
      run: docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=sqlPw3$secure' -e 'MSSQL_PID=Developer' -p 1433:1433 --name msssql -d mcr.microsoft.com/mssql/server:2019-latest
      
    #- name: Start Docker for Mongodb
    #  run: docker run -d -p 27017:27017 mongo
      
    #- name: Dump mssql docker logs
    #  run: docker logs msssql 
    # - name: Build with cake
    #   uses: ecampidoglio/cake-action@master
    #   env:
    #     NSTORE_MONGODB: mongodb://localhost/nstore
    #     NSTORE_MSSQL: Server=localhost;user id=sa;password=sqlPw3$secure
    #   with:
    #     script-path: build.cake
    #     target: ReleaseBuild  
    #     cake-version: "0.35.0"
        
